=== vg132/java_projects/IP4/trunk/1.2.1/cv.dtd
<!ELEMENT cv (contact,educations,language-skills,references)>
	<!ATTLIST cv xmlns:private CDATA #FIXED "http://www.vgsoftware.com/xmlnamespace/private">
	<!ATTLIST cv xmlns:company CDATA #FIXED "http://www.vgsoftware.com/xmlnamespace/company">
	<!ELEMENT contact (private:name,private:address,private:postcode,private:country?,private:phone*)>
		<!ELEMENT private:name (#PCDATA)>
			<!ATTLIST name xmlns CDATA #FIXED "http://www.vgsoftware.com/xmlnamespace/private">
		<!ELEMENT private:address (#PCDATA)>
			<!ATTLIST address xmlns CDATA #FIXED "http://www.vgsoftware.com/xmlnamespace/private">
		<!ELEMENT private:postcode (#PCDATA)>
			<!ATTLIST postcode xmlns CDATA #FIXED "http://www.vgsoftware.com/xmlnamespace/private">
		<!ELEMENT private:country (#PCDATA)>
			<!ATTLIST country xmlns CDATA #FIXED "http://www.vgsoftware.com/xmlnamespace/private">
		<!ELEMENT private:phone (#PCDATA)>
			<!ATTLIST private:phone name CDATA #IMPLIED>
			<!ATTLIST phone xmlns CDATA #FIXED "http://www.vgsoftware.com/xmlnamespace/private">
		<!ATTLIST contact xmlns CDATA #FIXED "http://www.vgsoftware.com/xmlnamespace/private">
	<!ELEMENT educations (education*)>
		<!ELEMENT education (#PCDATA)>
			<!ATTLIST education start CDATA #REQUIRED>
			<!ATTLIST education end CDATA #IMPLIED>
	<!ELEMENT language-skills (language*)>
		<!ELEMENT language (#PCDATA)>
			<!ATTLIST language level CDATA #REQUIRED>
	<!ELEMENT references (company:reference*)>
		<!ELEMENT company:reference (company:company,company:logo?,company:name,company:position?,company:address?,company:postcode?,company:country?,company:phone*)>
			<!ELEMENT company:company (#PCDATA)>
				<!ATTLIST company xmlns CDATA #FIXED "http://www.vgsoftware.com/xmlnamespace/company">
			<!ELEMENT company:logo (#PCDATA)>
				<!ATTLIST logo xmlns CDATA #FIXED "http://www.vgsoftware.com/xmlnamespace/company">
			<!ELEMENT company:name (#PCDATA)>
				<!ATTLIST name xmlns CDATA #FIXED "http://www.vgsoftware.com/xmlnamespace/company">
			<!ELEMENT company:position (#PCDATA)>
				<!ATTLIST position xmlns CDATA #FIXED "http://www.vgsoftware.com/xmlnamespace/company">
			<!ELEMENT company:address (#PCDATA)>
				<!ATTLIST address xmlns CDATA #FIXED "http://www.vgsoftware.com/xmlnamespace/company">
			<!ELEMENT company:postcode (#PCDATA)>
				<!ATTLIST postcode xmlns CDATA #FIXED "http://www.vgsoftware.com/xmlnamespace/company">
			<!ELEMENT company:country (#PCDATA)>
				<!ATTLIST country xmlns CDATA #FIXED "http://www.vgsoftware.com/xmlnamespace/company">
			<!ELEMENT company:phone (#PCDATA)>
				<!ATTLIST company:phone name CDATA #IMPLIED>
				<!ATTLIST phone xmlns CDATA #FIXED "http://www.vgsoftware.com/xmlnamespace/company">
			<!ATTLIST company xmlns CDATA #FIXED "http://www.vgsoftware.com/xmlnamespace/company">
	<!ENTITY myName "Viktor Gars">
	<!ENTITY logo SYSTEM "./logo.png">

=== vg132/java_projects/IP4/trunk/1.2.1/cvdtd.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE cv SYSTEM "1.2.1/cv.dtd">
<cv>
	<contact>
		<private:name>Viktor</private:name>
		<private:address>Dellvägen 45</private:address>
		<private:postcode>133 00</private:postcode>
		<private:country>Sweden</private:country>
		<private:phone name="home">08-541236</private:phone>
		<private:phone name="mobile">010-1231245</private:phone>
	</contact>
	<educations>
		<education start="2002" end="2005">DSV</education>
	</educations>
	<language-skills>
		<language level="modersmål">Svenska</language>
		<language level="mycket god">Engelska</language>
	</language-skills>
	<references>
		<company:reference>
			<company:company>VG Software</company:company>
			<company:logo>Logo</company:logo>
			<company:name>Kalle Anksson</company:name>
			<company:position>VD</company:position>
			<company:address>Dalvägen 45</company:address>
			<company:postcode>58401</company:postcode>
			<company:country>Sweden</company:country>
			<company:phone name="office">08-88552211</company:phone>
		</company:reference>
	</references>
</cv>
